# Generated by Django 5.0.2 on 2024-04-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
